---
name: Build

env:
  node_version: 18.13.0

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}

      - name: Test
        shell: bash
        run: npm run test

      - name: Build
        shell: bash
        run: npm run build
