---
name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    name: Node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ matrix.node-version }}
        uses: actions/checkout@v3

      - name: Setup and Test ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
        run: npm run test
